unique_ids:
  assets:
    standard-page.html: VNDZRMMGUBTWNGRKSJSBBW36OE4FBAD7
    theme.css: LVW7KW3ON4YCACCZB4E6FCZE2HINSITY
  forms:
    Form1: VPIK3DUBMF4MSY7IEGGM4RFG35DFFWMN
    Form1.ItemTemplate1: '1759719093593449256530069.7659'
    view_all: '1759805338828939277701198.6174'
  modules: {}
  scripts: {}
  server_modules: {}
