unique_ids:
  assets:
    standard-page.html: VNDZRMMGUBTWNGRKSJSBBW36OE4FBAD7
    theme.css: LVW7KW3ON4YCACCZB4E6FCZE2HINSITY
  forms:
    Form1: VPIK3DUBMF4MSY7IEGGM4RFG35DFFWMN
  modules: {}
  scripts: {}
  server_modules: {}
